version: '2'
services:
    # The Application / Server
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        volumes:
            - ./app:/app
        ports:
            - 3000:3000
            - 8080:8080
        environment:
            - 'DB_PORT=11210'
            - 'DB_HOST=database'

    # The Database
    database:
        image: couchbase:community
        ports:
            - 8091-8094:8091-8094
            - 11210:11210
