version: '2'
services:
    # The Application / Server
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        volumes:
            - ./app:/app
        ports:
            - 3000:3000
            - 8080:8080
        environment:
            - 'DB_PORT=3306'
            - 'DB_HOST=database'

    # The Database
    database:
        image: mysql:5.7
        # Uncomment below if you want to locally mount the database for whatever reason.
        # volumes:
        #     - ./dbdata:/var/lib/mysql
        environment:
            - 'MYSQL_DATABASE=database'
            - 'MYSQL_USER=esoodev'
            - 'MYSQL_PASSWORD=password'
            - 'MYSQL_ROOT_PASSWORD=password'
        ports:
            - '33061:3306'
